name: supabase_bloc_app
description: A Flutter app with Supabase, Firebase, BLoC, and Clean Architecture
publish_to: "none" # private package

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0

  # Supabase
  supabase_flutter: ^1.6.0

  # Firebase
  firebase_core: ^2.22.0
  firebase_messaging: ^14.6.0

  # UI
  cupertino_icons: ^1.0.5
  flutter_local_notifications: ^19.4.0 

  # Utilities
  equatable: ^2.0.7
  get_it: ^8.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
